version: "3"

services:
  nginx:
      image: nginx:latest
      ports:
          - "80:80"
      volumes:
          - .:/var/www/
          - ./config/nginx/local.conf:/etc/nginx/conf.d/local.conf
          - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      links:
          - fpm
  fpm:
      build: .
      volumes:
          - .:/var/www/
          - ./config/php/php.ini:/usr/local/etc/php.ini